# Generated by Django 4.0.3 on 2022-03-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_flan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='price',
            field=models.PositiveIntegerField(default=1000000),
        ),
    ]
