# Generated by Django 4.0.3 on 2022-03-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_flan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.PositiveIntegerField(default=10000000),
            preserve_default=False,
        ),
    ]
