# Generated by Django 4.0.3 on 2022-03-25 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
