# Generated by Django 4.0.3 on 2022-03-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
